### ISSUE TITLE
Routes for questions contain empty spaces

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/survey#2]
The routes for the questions contain blank spaces. Not a big issue, but we might want to convert them to '-' or just '%20'

**Comment by vinaypuppal** [comment]
its the problem with gh-pages or browser which is not encoding URL's or maybe because i am using **hashHistory** in react router . But without **hashHistory** deploying to gh-pages won't work

For https://survey.vinaypuppal.xyz/question/Which%20of%20the%20following%20resources%20have%20you%20used%20for%20learning%20HTML%20and%20CSS
 i used **browserHistory** in ReactRouter which seems to encode URL's

**Comment by duttakapil** [comment]
I see. It's fine, we can ignore this then
